site_name: Traversome
repo_url: https://github.com/Kinggerm/Traversome
edit_uri: edit/master/docs/

theme: 
  name: material
  palette:
    - scheme: slate
      primary: teal
      # accent: orange
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: default
      # primary: teal
      # accent: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  favicon: /images/favicon.ico
  icon:
    logo: material/library
    # admonition:
      # <type>

  features:
    - navigation.instant
    - navigation.tracking
    # - toc.integrate             # right-hav is always in toc
    - search.highlight
    - search.suggest
    - content.code.annotate # 
    # - navigation.indexes
    # - navigation.sections
    # - navigation.expand
    # - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  

extra:
  analytics:
    provider: 
    property:
  # version:
    # provider: mike

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search

nav:
  - About: index.md
  - Installation: installation.md
  - Quick Guide: quick-guide.md
  - Assembly Graph Estimation:
    - Introduction: assembly-graph/introduction.md
    - Example 1: assembly-graph/example-1.md
    - Example 2: . #assembly-graph/example-2.md
  - Graph Alignment Mapping:
    - Introduction: graph-alignment/introduction.md
  - Variant Frequency Estimation:
    - Introduction: frequency-estimation/introduction.md
  - Visualization:
    - Assembly Graphs in Bandage: .
    - Genome Structural Variants in xxx: .
    - ...: .